  SELECT * 
    FROM EMPLOYEES;
-- 실습1    
  SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE
    FROM EMPLOYEES;
-- 실습2
  SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID
    FROM DEPARTMENTS;
    
-- 3. 중복제거기능
-- 중복을 제거하면 데이터의 종류를 알 수 있다

  SELECT DISTINCT DEPARTMENT_ID
    FROM EMPLOYEES;

-- 컬럼 여러개를 기준으로 중복 제거
SELECT DISTINCT JOB_ID, DEPARTMENT_ID
    FROM EMPLOYEES;
    
-- 4.별칭정하기
SELECT EMPLOYEE_ID, SALARY, SALARY*12 AS "연봉"
  FROM EMPLOYEES;
  
SELECT EMPLOYEE_ID 직원아이디
        ,EMPLOYEE_ID "직원아이디"
        ,EMPLOYEE_ID AS 직원아이디
        ,EMPLOYEE_ID AS "직원아이디"
  FROM EMPLOYEES;
  
-- 입사한 다음 날을 계약일이라고 칭해보자.
-- 직원의 FIRST_NAME, 입사일, 계약일을 출력해보자.

SELECT FIRST_NAME
        , HIRE_DATE AS 입사일
        , HIRE_DATE+1 AS 계약일
  FROM EMPLOYEES;
  
-- 5.NULL
-- 데이터의 값이 비어있는 상태

INSERT INTO EMPLOYEES(
    EMPLOYEE_ID, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID)
VALUES (208, '홍진성', 'ZEROTICKET', SYSDATE,'IT_PROG');

COMMIT;

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, SALARY+100
  FROM EMPLOYEES;